language: ruby
matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfile.ruby-1.8.7
      script: bundle exec rspec spec

    - rvm: 1.9.3
      gemfile: Gemfile 
      script: bundle exec rake ci

    - rvm: 2.0.0
      gemfile: Gemfile 
      script: bundle exec rake ci

    - rvm: 2.1.0
      gemfile: Gemfile 
      script: bundle exec rake ci

